// SPDX-License-Identifier: Apache-2.0
use std::{collections::BTreeMap, fmt::Write};

use super::plan::{Plan, count, enum_name, field_cpp, identifier, optional, scalar_cpp, type_name};
use crate::{
    codegen::{c_identifier, type_name as c_type_name},
    semantic::{FieldDefault, FieldSymbol, ResolvedType},
};

pub(super) fn emit(plan: &Plan<'_>, files: &mut BTreeMap<String, String>) {
    let name = &plan.options.name;
    // Keep system/Wirelink dependencies global, then isolate schema C typedefs
    // (e.g. Mode -> mode_t) from system typedefs in the C++ bridge.
    files.insert("src/native.hpp".into(), format!("/* SPDX-License-Identifier: Apache-2.0 */\n#pragma once\n#include <cfloat>\n#include <cstddef>\n#include <cstdint>\n#include <wirelink/codec.h>\n// Only passive values cross this namespace. Endpoint callbacks stay in C.\nnamespace {name}::wlc_native {{\n#include \"{name}_values.h\"\n}}\n"));
    let native = files.get_mut("src/native.hpp").unwrap();
    native.push_str("// C enum macros must not rewrite scoped C++ enum member names.\n");
    for enumeration in &plan.enums {
        for value in &enumeration.values {
            writeln!(
                native,
                "#undef {}",
                crate::codegen::upper_snake(&value.name)
            )
            .unwrap();
        }
    }
    let mut types = format!(
        "/* SPDX-License-Identifier: Apache-2.0 */\n// Generated by WLC. All fields own their data.\n#pragma once\n#include <array>\n#include <cstdint>\n#include <optional>\n#include <string>\n#include <vector>\n\nnamespace {name} {{\n"
    );
    for enumeration in &plan.enums {
        writeln!(
            types,
            "enum class {} : std::int32_t {{",
            type_name(&enumeration.name)
        )
        .unwrap();
        for value in &enumeration.values {
            writeln!(types, "  {} = {},", enum_name(&value.name), value.number).unwrap();
        }
        types.push_str("};\n\n");
    }
    for message in &plan.messages {
        writeln!(types, "struct {} {{", type_name(&message.name)).unwrap();
        for field in &message.fields {
            writeln!(
                types,
                "  {} {}{{}};",
                field_cpp(field),
                identifier(&field.name)
            )
            .unwrap();
        }
        for field in &message.fields {
            if field.default.is_some() {
                let f = identifier(&field.name);
                writeln!(
                    types,
                    "  {} {f}_or_default() const {{ return {f}.value_or({}); }}",
                    scalar_cpp(&field.ty),
                    default_cpp(field)
                )
                .unwrap();
            }
        }
        types.push_str("};\n\n");
    }
    writeln!(types, "}} // namespace {name}").unwrap();
    files.insert(format!("include/{name}/types.hpp"), types);

    let mut methods = String::new();
    for rpc in &plan.profile.rpc_services {
        writeln!(methods, "  wirelink::Result<{}> {}(const {}& request,\n      std::chrono::milliseconds timeout = std::chrono::seconds(1));",
            type_name(&rpc.response_name), identifier(&rpc.name), type_name(&rpc.request_name)).unwrap();
    }
    files.insert(format!("include/{name}/client.hpp"), format!("/* SPDX-License-Identifier: Apache-2.0 */\n// Generated by WLC.\n#pragma once\n#include <{name}/types.hpp>\n#include <wirelink/cpp/session.hpp>\n#include <chrono>\n#include <utility>\n\nnamespace {name} {{\nclass Client {{\npublic:\n  static wirelink::Result<Client> connect(const wirelink::UdpOptions& options);\n  Client(Client&&) noexcept = default;\n  Client& operator=(Client&&) noexcept = default;\n  Client(const Client&) = delete;\n  Client& operator=(const Client&) = delete;\n{methods}  void close() noexcept {{ session_.close(); }}\n  bool is_open() const noexcept {{ return session_.is_open(); }}\n  std::uint16_t local_port() const noexcept {{ return session_.local_port(); }}\nprivate:\n  explicit Client(wirelink::Session session) : session_(std::move(session)) {{}}\n  wirelink::Session session_;\n}};\n}} // namespace {name}\n"));

    let mut values = format!(
        "/* SPDX-License-Identifier: Apache-2.0 */\n// Generator-private owned conversions; never installed as a public header.\n#pragma once\n#include <{name}/types.hpp>\n#include \"native.hpp\"\n#include <algorithm>\n\nnamespace {name}::wlc_detail {{\n"
    );
    for message in &plan.messages {
        let ty = type_name(&message.name);
        let c = c_type_name(&message.name);
        writeln!(values, "inline bool to_c(const {ty}& input, wlc_native::{c}_value_t& output) {{\n  (void)input;\n  wlc_native::{c}_value_clear(&output);").unwrap();
        for field in &message.fields {
            let f = identifier(&field.name);
            let cf = c_identifier(&field.name);
            let expr = if optional(field) {
                format!("(*input.{f})")
            } else {
                format!("input.{f}")
            };
            let presence = if optional(field) {
                format!("input.{f}.has_value()")
            } else {
                "true".to_owned()
            };
            writeln!(
                values,
                "  output.has_{cf} = {presence};\n  if (output.has_{cf}) {{"
            )
            .unwrap();
            if count(field).is_some() {
                writeln!(
                    values,
                    "    std::copy({expr}.begin(), {expr}.end(), output.{cf});"
                )
                .unwrap();
            } else {
                match &field.ty {
                    ResolvedType::String | ResolvedType::Bytes => {
                        writeln!(values, "    if ({expr}.size() > {}U) return false;\n    output.{cf}.length = {expr}.size();\n    std::copy({expr}.begin(), {expr}.end(), output.{cf}.data);", field.max_length.unwrap()).unwrap();
                    }
                    ResolvedType::Message { .. } => {
                        writeln!(values, "    if (!to_c({expr}, output.{cf})) return false;")
                            .unwrap();
                    }
                    ResolvedType::Enum { .. } => {
                        writeln!(
                            values,
                            "    output.{cf} = static_cast<std::int32_t>({expr});"
                        )
                        .unwrap();
                    }
                    _ => {
                        writeln!(values, "    output.{cf} = {expr};").unwrap();
                    }
                }
            }
            values.push_str("  }\n");
        }
        writeln!(values, "  return true;\n}}\n\ninline {ty} from_c(const wlc_native::{c}_value_t& input) {{\n  (void)input;\n  {ty} output{{}};").unwrap();
        for field in &message.fields {
            let f = identifier(&field.name);
            let cf = c_identifier(&field.name);
            writeln!(values, "  if (input.has_{cf}) {{").unwrap();
            let dest = if optional(field) {
                writeln!(values, "    output.{f}.emplace();").unwrap();
                format!("(*output.{f})")
            } else {
                format!("output.{f}")
            };
            if let Some(n) = count(field) {
                writeln!(values, "    std::copy_n(input.{cf}, {n}, {dest}.begin());").unwrap();
            } else {
                match &field.ty {
                    ResolvedType::String | ResolvedType::Bytes => {
                        writeln!(values, "    {dest}.assign(input.{cf}.data, input.{cf}.data + input.{cf}.length);").unwrap();
                    }
                    ResolvedType::Message { .. } => {
                        writeln!(values, "    {dest} = from_c(input.{cf});").unwrap();
                    }
                    ResolvedType::Enum { .. } => {
                        writeln!(
                            values,
                            "    {dest} = static_cast<{}>(input.{cf});",
                            scalar_cpp(&field.ty)
                        )
                        .unwrap();
                    }
                    _ => {
                        writeln!(values, "    {dest} = input.{cf};").unwrap();
                    }
                }
            }
            values.push_str("  }\n");
        }
        values.push_str("  return output;\n}\n\n");
    }
    writeln!(values, "}} // namespace {name}::wlc_detail").unwrap();
    files.insert("src/values.hpp".into(), values);

    let mut bridge_header = format!(
        "/* SPDX-License-Identifier: Apache-2.0 */\n#pragma once\n#include <stddef.h>\n#include <wirelink/endpoint.h>\n#include <wirelink/rpc_result.h>\n#ifdef __cplusplus\nextern \"C\" {{\n#endif\nsize_t {name}_sdk_endpoint_size(void);\nsize_t {name}_sdk_endpoint_alignment(void);\nwl_err_t {name}_sdk_endpoint_init(void*, wl_endpoint_driver_t*);\nvoid {name}_sdk_endpoint_close(void*);\n"
    );
    let mut bridge_source = format!(
        "/* SPDX-License-Identifier: Apache-2.0 */\n// Endpoint callbacks are compiled in C with exactly the runtime's C types.\n#include \"endpoint.h\"\n#include \"{name}_endpoint.h\"\n#include <wirelink/platform.h>\n#include <string.h>\nsize_t {name}_sdk_endpoint_size(void) {{ return sizeof({name}_endpoint_t); }}\nsize_t {name}_sdk_endpoint_alignment(void) {{ return _Alignof({name}_endpoint_t); }}\nwl_err_t {name}_sdk_endpoint_init(void* storage, wl_endpoint_driver_t* driver) {{\n  {name}_endpoint_t* endpoint = storage;\n  memset(endpoint, 0, sizeof(*endpoint));\n  const wl_err_t status = {name}_endpoint_init(endpoint, wl_platform_environment());\n  if (status == WL_OK) *driver = {name}_endpoint_driver(endpoint);\n  return status;\n}}\nvoid {name}_sdk_endpoint_close(void* storage) {{ (void){name}_endpoint_close(storage); }}\n"
    );
    for rpc in &plan.profile.rpc_services {
        let method = c_identifier(&rpc.name);
        writeln!(
            bridge_header,
            "wl_rpc_completion_t {name}_sdk_{method}(void*, const void*, void*, uint32_t);"
        )
        .unwrap();
        writeln!(bridge_source, "wl_rpc_completion_t {name}_sdk_{method}(void* endpoint, const void* request, void* response, uint32_t timeout_ms) {{\n  return {name}_endpoint_{method}_sync(endpoint, request, response, timeout_ms);\n}}").unwrap();
    }
    bridge_header.push_str("#ifdef __cplusplus\n}\n#endif\n");
    files.insert("src/endpoint.h".into(), bridge_header);
    files.insert("src/endpoint.c".into(), bridge_source);
    let mut source = format!(
        "/* SPDX-License-Identifier: Apache-2.0 */\n// Generated by WLC.\n#include <{name}/client.hpp>\n#include \"values.hpp\"\n#include \"endpoint.h\"\n#include <memory>\n#include <new>\n\nnamespace {name} {{\nusing namespace wlc_native;\nnamespace {{\nvoid deallocate(void* pointer) noexcept {{\n  ::operator delete(pointer, std::align_val_t({name}_sdk_endpoint_alignment()));\n}}\nvoid* create(wl_endpoint_driver_t& driver, wirelink::Error& error) {{\n  std::unique_ptr<void, decltype(&deallocate)> endpoint(\n      ::operator new({name}_sdk_endpoint_size(), std::align_val_t({name}_sdk_endpoint_alignment())), deallocate);\n  const int status = {name}_sdk_endpoint_init(endpoint.get(), &driver);\n  if (status != WL_OK) {{\n    error = wirelink::Error::local(status);\n    return nullptr;\n  }}\n  return endpoint.release();\n}}\nvoid destroy(void* pointer) noexcept {{\n  {name}_sdk_endpoint_close(pointer);\n  deallocate(pointer);\n}}\n}} // namespace\n\nwirelink::Result<Client> Client::connect(const wirelink::UdpOptions& options) {{\n  auto session = wirelink::Session::connect(options, {{create, destroy}});\n  if (!session) return session.error();\n  return Client(std::move(session).value());\n}}\n\n"
    );
    for rpc in &plan.profile.rpc_services {
        let method = identifier(&rpc.name);
        let c_method = c_identifier(&rpc.name);
        let req = type_name(&rpc.request_name);
        let resp = type_name(&rpc.response_name);
        let c_req = c_type_name(&rpc.request_name);
        let c_resp = c_type_name(&rpc.response_name);
        writeln!(source, "wirelink::Result<{resp}> Client::{method}(const {req}& request,\n    std::chrono::milliseconds timeout) {{\n  if (timeout.count() <= 0 || timeout.count() > INT32_MAX)\n    return wirelink::Error::local(WL_ERR_INVALID_ARG);\n  struct Call {{\n    {c_req}_value_t request{{}};\n    {c_resp}_value_t response{{}};\n    std::uint32_t timeout_ms;\n  }} call;\n  if (!wlc_detail::to_c(request, call.request))\n    return wirelink::Error::local(WL_ERR_INVALID_ARG);\n  call.timeout_ms = static_cast<std::uint32_t>(timeout.count());\n  const auto completion = session_.invoke([](void* endpoint, void* context) noexcept {{\n    auto& state = *static_cast<Call*>(context);\n    return {name}_sdk_{c_method}(endpoint,\n        &state.request, &state.response, state.timeout_ms);\n  }}, &call);\n  if (completion.status != WL_RPC_SUCCESS)\n    return wirelink::Error::from_completion(completion);\n  try {{\n    return wlc_detail::from_c(call.response);\n  }} catch (const std::bad_alloc&) {{\n    return wirelink::Error::local(WL_ERR_NO_MEM);\n  }}\n}}\n").unwrap();
    }
    writeln!(source, "}} // namespace {name}").unwrap();
    files.insert("src/client.cpp".into(), source);
}

fn default_cpp(field: &FieldSymbol) -> String {
    let (_, signed, unsigned, literal, _) = crate::codegen::field_descriptor_data(field);
    match field.default.as_ref().unwrap() {
        FieldDefault::String(s) => format!("std::string({literal}, {})", s.len()),
        FieldDefault::Bool(b) => b.to_string(),
        FieldDefault::Enum(n) => format!("static_cast<{}>({n})", scalar_cpp(&field.ty)),
        FieldDefault::Int64(i64::MIN) => "(-INT64_C(9223372036854775807) - 1)".into(),
        FieldDefault::Int64(_) => signed,
        FieldDefault::Int8(_) | FieldDefault::Int16(_) | FieldDefault::Int32(_) => signed,
        _ => format!("UINT64_C({unsigned})"),
    }
}
